### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by cantonic** [masolin/linter-rails-best-practices#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: [linter-rails-best-practices](https://github.com/masolin/linter-rails-best-practices) package, v0.2.2
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/can/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:12:9
    at lint (/Users/can/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:8:7)
    at Object.provider.lint (/Users/can/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:62:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/can/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/can/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/can/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/can/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/can/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:19.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -0:18.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:10.3.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:09.1.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:04.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "live-doc-viewer",
      "cucumber",
      "cucumber-step",
      "minimap",
      "atom-pair"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "native-ui",
      "railscasts-prime-syntax"
    ]
  },
  "linter-rails-best-practices": {
    "executablePath": "/Users/can/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rails_best_practices-1.15.7"
  }
}
```
### Installed Packages

``` coffee
# User
atom-everydayrails-rspec, v0.2.0
autocomplete-plus, v2.27.1
autocomplete-ruby, v0.1.0
browser-plus, v0.0.54
color-tabs, v0.1.8
file-icons, v1.6.14
git-diff-details, v0.21.0
html2haml, v0.10.0
language-haml, v0.23.15
line-diff-details, v1.2.0
linter, v1.11.3
linter-haml, v1.1.0
linter-rails-best-practices, v0.2.2
linter-rubocop, v0.4.7
native-ui, v0.17.0
rails-i18n, v0.1.3
rails-model-schema, v0.7.3
railscasts-prime-syntax, v1.0.1
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-test-switcher, v1.2.0
terminal-plus, v0.14.5
travis-ci-status, v1.0.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by FinnWoelm** [comment]
Is `/Users/can/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rails_best_practices-1.15.7` the result of `which rails_best_practices`?

**Comment by masolin** [comment]
Hi @cantonic, your `executablePath` was linked to a folder, not an executable file.
You uses `rbenv`, so you could use `rbenv which rails_best_practices` to get the path you needed.

**Comment by cantonic** [comment]
thanks guys 😄
