### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by maevetierney** [masolin/linter-rails-best-practices#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-rails-best-practices](https://github.com/masolin/linter-rails-best-practices) package, v0.2.2
### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /Users/MaeveTierney/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262

Error: spawn ENOTDIR
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Users/MaeveTierney/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/Users/MaeveTierney/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/MaeveTierney/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:12:9
    at lint (/Users/MaeveTierney/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:8:7)
    at Object.provider.lint (/Users/MaeveTierney/.atom/packages/linter-rails-best-practices/lib/linter-rails-best-practices.coffee:62:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/MaeveTierney/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/MaeveTierney/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/MaeveTierney/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/MaeveTierney/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/MaeveTierney/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/MaeveTierney/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/MaeveTierney/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/MaeveTierney/.atom/packages/linter/lib/helpers.coffee:25:18
```
### Commands

```
     -0:28.2.0 application:add-project-folder (atom-pane.pane.active)
     -0:10.5.0 tree-view:remove-project-folder (div.header.list-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "climate-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose, v0.0.2
autoclose-html, v0.23.0
climate-syntax, v5.0.0
intentions, v1.0.5
linter, v1.11.14
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
linter-rails-best-practices, v0.2.2
linter-ruby, v1.2.2
linter-spell, v0.8.0
linter-spell-html, v0.4.0
pigments, v0.31.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Do you have `rails_best_practices` installed? Does the error go away if you put the full path into the "rails_best_practices Executable Path" setting? You can find that by running `which rails_best_practices`.
