### ISSUE TITLE
Failed to spawn command rails_best_practices

### ISSUE THREAD

**Issue by ducle** [masolin/linter-rails-best-practices#6]
Make sure rails_best_practices is installed and on your PATH

The Chrome inspection gives this:

`rails_best_practices`. Make sure `rails_best_practices` is installed and on your PATH
    at BufferedProcess.handleError (/Users/admin/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:388:23)
    at ChildProcess.<anonymous> (/Users/admin/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Arcanemagus** [comment]
It looks like you haven't installed `rails_best_practices` yet, you can do so by following the [installation steps](https://github.com/masolin/linter-rails-best-practices#rails_best_practices-installation).
